*******************************************************************************
****** VCO_sch1 schematic PD  <vs>  VCO_sch1 layout PD
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(g45n1svt) MOS                                   13      13
(g45p1svt) MOS                                   13      13
                                             ------  ------
Total                                            26      26

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(g45n1svt) MOS                                   13      13           3       3
(g45p1svt) MOS                                   13      13           3       3
(g45n1svt:SerMos2#1) MosBlk                       -       -           5       5
(g45p1svt:SerMos2#1) MosBlk                       -       -           5       5
                                             ------  ------      ------  ------
Total                                            26      26          16      16

Schematic and Layout Match
