0 0 dataAuditErrors
1 0 non45Errors
2 0 offGridErrors
85 0 offGridShapeErrors: off grid polygon on layer Bondpad
88 0 offGridShapeErrors: off grid polygon on layer CapMetal
91 0 offGridShapeErrors: off grid polygon on layer Cont
94 0 offGridShapeErrors: off grid polygon on layer ESDdummy
97 0 offGridShapeErrors: off grid polygon on layer INDdummy
100 0 offGridShapeErrors: off grid polygon on layer M1Resdum
103 0 offGridShapeErrors: off grid polygon on layer M2Resdum
106 0 offGridShapeErrors: off grid polygon on layer M3Resdum
109 0 offGridShapeErrors: off grid polygon on layer M4Resdum
112 0 offGridShapeErrors: off grid polygon on layer M5Resdum
115 0 offGridShapeErrors: off grid polygon on layer M6Resdum
118 0 offGridShapeErrors: off grid polygon on layer M7Resdum
121 0 offGridShapeErrors: off grid polygon on layer M8Resdum
124 0 offGridShapeErrors: off grid polygon on layer M9Resdum
127 0 offGridShapeErrors: off grid polygon on layer M10Resdum
130 0 offGridShapeErrors: off grid polygon on layer M11Resdum
133 0 offGridShapeErrors: off grid polygon on layer Metal1
136 0 offGridShapeErrors: off grid polygon on layer Metal2
139 0 offGridShapeErrors: off grid polygon on layer Metal3
142 0 offGridShapeErrors: off grid polygon on layer Metal4
145 0 offGridShapeErrors: off grid polygon on layer Metal5
148 0 offGridShapeErrors: off grid polygon on layer Metal6
151 0 offGridShapeErrors: off grid polygon on layer Metal7
154 0 offGridShapeErrors: off grid polygon on layer Metal8
157 0 offGridShapeErrors: off grid polygon on layer Metal9
160 0 offGridShapeErrors: off grid polygon on layer Metal10
163 0 offGridShapeErrors: off grid polygon on layer Metal11
166 0 offGridShapeErrors: off grid polygon on layer NPNdummy
169 0 offGridShapeErrors: off grid polygon on layer Nburied
172 0 offGridShapeErrors: off grid polygon on layer Nhvt
175 0 offGridShapeErrors: off grid polygon on layer Nimp
178 0 offGridShapeErrors: off grid polygon on layer Nlvt
181 0 offGridShapeErrors: off grid polygon on layer Nwell
184 0 offGridShapeErrors: off grid polygon on layer Nzvt
187 0 offGridShapeErrors: off grid polygon on layer Oxide
190 0 offGridShapeErrors: off grid polygon on layer Oxide_thk
193 0 offGridShapeErrors: off grid polygon on layer PNPdummy
196 0 offGridShapeErrors: off grid polygon on layer Phvt
199 0 offGridShapeErrors: off grid polygon on layer Pimp
202 0 offGridShapeErrors: off grid polygon on layer Plvt
205 0 offGridShapeErrors: off grid polygon on layer Poly
208 0 offGridShapeErrors: off grid polygon on layer Psub
211 0 offGridShapeErrors: off grid polygon on layer ResWdum
214 0 offGridShapeErrors: off grid polygon on layer Resdum
217 0 offGridShapeErrors: off grid polygon on layer SiProt
220 0 offGridShapeErrors: off grid polygon on layer Via1
223 0 offGridShapeErrors: off grid polygon on layer Via2
226 0 offGridShapeErrors: off grid polygon on layer Via3
229 0 offGridShapeErrors: off grid polygon on layer Via4
232 0 offGridShapeErrors: off grid polygon on layer Via5
235 0 offGridShapeErrors: off grid polygon on layer Via6
238 0 offGridShapeErrors: off grid polygon on layer Via7
241 0 offGridShapeErrors: off grid polygon on layer Via8
244 0 offGridShapeErrors: off grid polygon on layer Via9
247 0 offGridShapeErrors: off grid polygon on layer Via10
249 0 non45 degree polygon on layer Bondpad
251 0 non45 degree polygon on layer CapMetal
253 0 non45 degree polygon on layer Cont
255 0 non45 degree polygon on layer ESDdummy
257 0 non45 degree polygon on layer INDdummy
259 0 non45 degree polygon on layer M1Resdum
261 0 non45 degree polygon on layer M2Resdum
263 0 non45 degree polygon on layer M3Resdum
265 0 non45 degree polygon on layer M4Resdum
267 0 non45 degree polygon on layer M5Resdum
269 0 non45 degree polygon on layer M6Resdum
271 0 non45 degree polygon on layer M7Resdum
273 0 non45 degree polygon on layer M8Resdum
275 0 non45 degree polygon on layer M9Resdum
277 0 non45 degree polygon on layer M10Resdum
279 0 non45 degree polygon on layer M11Resdum
281 0 non45 degree polygon on layer Metal1
283 0 non45 degree polygon on layer Metal2
285 0 non45 degree polygon on layer Metal3
287 0 non45 degree polygon on layer Metal4
289 0 non45 degree polygon on layer Metal5
291 0 non45 degree polygon on layer Metal6
293 0 non45 degree polygon on layer Metal7
295 0 non45 degree polygon on layer Metal8
297 0 non45 degree polygon on layer Metal9
299 0 non45 degree polygon on layer Metal10
301 0 non45 degree polygon on layer Metal11
303 0 non45 degree polygon on layer NPNdummy
305 0 non45 degree polygon on layer Nburied
307 0 non45 degree polygon on layer Nhvt
309 0 non45 degree polygon on layer Nimp
311 0 non45 degree polygon on layer Nlvt
313 0 non45 degree polygon on layer Nwell
315 0 non45 degree polygon on layer Nzvt
317 0 non45 degree polygon on layer Oxide
319 0 non45 degree polygon on layer Oxide_thk
321 0 non45 degree polygon on layer PNPdummy
323 0 non45 degree polygon on layer Phvt
325 0 non45 degree polygon on layer Pimp
327 0 non45 degree polygon on layer Plvt
329 0 non45 degree polygon on layer Poly
331 0 non45 degree polygon on layer Psub
333 0 non45 degree polygon on layer ResWdum
335 0 non45 degree polygon on layer Resdum
337 0 non45 degree polygon on layer SiProt
339 0 non45 degree polygon on layer Via1
341 0 non45 degree polygon on layer Via2
343 0 non45 degree polygon on layer Via3
345 0 non45 degree polygon on layer Via4
347 0 non45 degree polygon on layer Via5
349 0 non45 degree polygon on layer Via6
351 0 non45 degree polygon on layer Via7
353 0 non45 degree polygon on layer Via8
355 0 non45 degree polygon on layer Via9
357 0 non45 degree polygon on layer Via10
358 0 acute angle on layer Bondpad
359 0 acute angle on layer ESDdummy
360 0 acute angle on layer INDdummy
361 0 acute angle on layer M1Resdum
362 0 acute angle on layer M2Resdum
363 0 acute angle on layer M3Resdum
364 0 acute angle on layer M4Resdum
365 0 acute angle on layer M5Resdum
366 0 acute angle on layer M6Resdum
367 0 acute angle on layer M7Resdum
368 0 acute angle on layer M8Resdum
369 0 acute angle on layer M9Resdum
370 0 acute angle on layer M10Resdum
371 0 acute angle on layer M11Resdum
372 0 acute angle on layer NPNdummy
373 0 acute angle on layer PNPdummy
374 0 acute angle on layer Psub
375 0 acute angle on layer ResWdum
376 0 acute angle on layer Resdum
415 0 NZVT.X.4: Only one Oxide region may be in an Nzvt region
558 0 BONDPAD.L.1: Bondpad length must be >= 68.0 um
562 0 NBL.X.1: Nburied must have an Nwell isolation ring
623 0 NZVT.O.1: Minimum and maximum Nzvt to Active Area overlap == 0.16 um
836 0 VIAk.X.3_VIAk.X.4: Metal1 through Metal6 stack must have two or more stacked Vias at all levels
841 0 VIAk.X.3_VIAk.X.4: Metal2 through Metal7 stack must have two or more stacked Vias at all levels
846 0 VIAk.X.3_VIAk.X.4: Metal3 through Metal8 stack must have two or more stacked Vias at all levels
851 0 VIAk.X.3_VIAk.X.4: Metal4 through Metal9 stack must have two or more stacked Vias at all levels
1141 0 POLY.SE.3: Maximum Poly segment length (width < 0.14) between two contacts >= 12.0 um
1150 0 VIA1.E.3: At least 2 Via1 must be used to join Metal1 and Metal2 when they are within 3.0um of a metal plate (Metal1/Metal2) when the metal plate size is has width > 1.5 and length > 1.5
1159 0 VIA2.E.3: At least 2 Via2 must be used to join Metal2 and Metal3 when they are within 3.0um of a metal plate (Metal2/Metal3) when the metal plate size is has width > 1.5 and length > 1.5
1168 0 VIA3.E.3: At least 2 Via3 must be used to join Metal3 and Metal4 when they are within 3.0um of a metal plate (Metal3/Metal4) when the metal plate size is has width > 1.5 and length > 1.5
1177 0 VIA4.E.3: At least 2 Via4 must be used to join Metal4 and Metal5 when they are within 3.0um of a metal plate (Metal4/Metal5) when the metal plate size is has width > 1.5 and length > 1.5
1186 0 VIA5.E.3: At least 2 Via5 must be used to join Metal5 and Metal6 when they are within 3.0um of a metal plate (Metal5/Metal6) when the metal plate size is has width > 1.5 and length > 1.5
1195 0 VIA6.E.3: At least 2 Via6 must be used to join Metal6 and Metal7 when they are within 3.0um of a metal plate (Metal6/Metal7) when the metal plate size is has width > 1.5 and length > 1.5
1204 0 VIA7.E.3: At least 2 Via7 must be used to join Metal7 and Metal8 when they are within 3.0um of a metal plate (Metal7/Metal8) when the metal plate size is has width > 1.5 and length > 1.5
1213 0 VIA8.E.3: At least 2 Via8 must be used to join Metal8 and Metal9 when they are within 3.0um of a metal plate (Metal8/Metal9) when the metal plate size is has width > 1.5 and length > 1.5
1225 0 BONDPAD.SP.5: Bondpad Metal1 slot to Bondpad Metal1 slot spacing must be == 1.50
1229 0 BONDPAD.W.4: Bondpad Metal1 slot width must be == 1.00
1240 0 BONDPAD.R.1: Minimum Bondpad Via1 inside Metal1 to Metal2 crossing must be >= 16.0
1245 0 BONDPAD.SP.5: Bondpad Metal2 slot to Bondpad Metal2 slot spacing must be == 1.50
1249 0 BONDPAD.W.4: Bondpad Metal2 slot width must be == 1.00
1260 0 BONDPAD.R.1: Minimum Bondpad Via2 inside Metal2 to Metal3 crossing must be >= 16.0
1265 0 BONDPAD.SP.5: Bondpad Metal3 slot to Bondpad Metal3 slot spacing must be == 1.50
1269 0 BONDPAD.W.4: Bondpad Metal3 slot width must be == 1.00
1280 0 BONDPAD.R.1: Minimum Bondpad Via3 inside Metal3 to Metal4 crossing must be >= 16.0
1285 0 BONDPAD.SP.5: Bondpad Metal4 slot to Bondpad Metal4 slot spacing must be == 1.50
1289 0 BONDPAD.W.4: Bondpad Metal4 slot width must be == 1.00
1300 0 BONDPAD.R.1: Minimum Bondpad Via4 inside Metal4 to Metal5 crossing must be >= 16.0
1305 0 BONDPAD.SP.5: Bondpad Metal5 slot to Bondpad Metal5 slot spacing must be == 1.50
1309 0 BONDPAD.W.4: Bondpad Metal5 slot width must be == 1.00
1320 0 BONDPAD.R.1: Minimum Bondpad Via5 inside Metal5 to Metal6 crossing must be >= 16.0
1325 0 BONDPAD.SP.5: Bondpad Metal6 slot to Bondpad Metal6 slot spacing must be == 1.50
1329 0 BONDPAD.W.4: Bondpad Metal6 slot width must be == 1.00
1340 0 BONDPAD.R.1: Minimum Bondpad Via6 inside Metal6 to Metal7 crossing must be >= 16.0
1345 0 BONDPAD.SP.5: Bondpad Metal7 slot to Bondpad Metal7 slot spacing must be == 1.50
1349 0 BONDPAD.W.4: Bondpad Metal7 slot width must be == 1.00
1360 0 BONDPAD.R.1: Minimum Bondpad Via7 inside Metal7 to Metal8 crossing must be >= 16.0
1365 0 BONDPAD.SP.5: Bondpad Metal8 slot to Bondpad Metal8 slot spacing must be == 1.50
1369 0 BONDPAD.W.4: Bondpad Metal8 slot width must be == 1.00
1380 0 BONDPAD.R.1: Minimum Bondpad Via8 inside Metal8 to Metal9 crossing must be >= 16.0
1385 0 BONDPAD.SP.5: Bondpad Metal9 slot to Bondpad Metal9 slot spacing must be == 1.50
1389 0 BONDPAD.W.4: Bondpad Metal9 slot width must be == 1.00
1400 0 BONDPAD.R.2: Minimum Bondpad Via9 inside Metal9 to Metal10 crossing must be >= 4.0
1405 0 BONDPAD.SP.5: Bondpad Metal10 slot to Bondpad Metal10 slot spacing must be == 1.50
1409 0 BONDPAD.W.4: Bondpad Metal10 slot width must be == 1.00
1414 0 BONDPAD.R.2: Minimum Bondpad Via10 inside Metal10 to Metal11 crossing must be >= 4.0
1793 0 OXIDE.L.1_OXIDE.L.2: Maximum Oxide length between two contacts (when the Oxide width is <= 0.18um) must be <= 12.0um and Maximum Oxide length between one contact and the end of the Oxide line (when the Oxide width is <= 0.18um) must be <= 6.0um
1821 0 BONDPAD.W.5: Bondpad Metal1 outside Metal1 ring width must be == 5.00
1849 0 BONDPAD.W.5: Bondpad Metal2 outside Metal2 ring width must be == 5.00
1877 0 BONDPAD.W.5: Bondpad Metal3 outside Metal3 ring width must be == 5.00
1905 0 BONDPAD.W.5: Bondpad Metal4 outside Metal4 ring width must be == 5.00
1933 0 BONDPAD.W.5: Bondpad Metal5 outside Metal5 ring width must be == 5.00
1961 0 BONDPAD.W.5: Bondpad Metal6 outside Metal6 ring width must be == 5.00
1989 0 BONDPAD.W.5: Bondpad Metal7 outside Metal7 ring width must be == 5.00
2017 0 BONDPAD.W.5: Bondpad Metal8 outside Metal8 ring width must be == 5.00
2045 0 BONDPAD.W.5: Bondpad Metal9 outside Metal9 ring width must be == 5.00
2073 0 BONDPAD.W.5: Bondpad Metal10 outside Metal10 ring width must be == 5.00
2092 0 VIA1.X.2: Metal1 must connect to Metal2 with >= 4 Via1 spaced < 0.30 um or >= 9 Via1 spaced < 0.60 um
2111 0 VIA2.X.2: Metal2 must connect to Metal3 with >= 4 Via2 spaced < 0.30 um or >= 9 Via2 spaced < 0.60 um
2130 0 VIA3.X.2: Metal3 must connect to Metal4 with >= 4 Via3 spaced < 0.30 um or >= 9 Via3 spaced < 0.60 um
2149 0 VIA4.X.2: Metal4 must connect to Metal5 with >= 4 Via4 spaced < 0.30 um or >= 9 Via4 spaced < 0.60 um
2168 0 VIA5.X.2: Metal5 must connect to Metal6 with >= 4 Via5 spaced < 0.30 um or >= 9 Via5 spaced < 0.60 um
2187 0 VIA6.X.2: Metal6 must connect to Metal7 with >= 4 Via6 spaced < 0.30 um or >= 9 Via6 spaced < 0.60 um
2206 0 VIA7.X.2: Metal7 must connect to Metal8 with >= 4 Via7 spaced < 0.30 um or >= 9 Via7 spaced < 0.60 um
2225 0 VIA8.X.2: Metal8 must connect to Metal9 with >= 4 Via8 spaced < 0.30 um or >= 9 Via8 spaced < 0.60 um
2245 0 VIA1.X.1: Metal1 must connect to Metal2 with >= 2 Via1 spaced < 0.30 um or >= 4 Via1 spaced < 0.60 um
2265 0 VIA2.X.1: Metal2 must connect to Metal3 with >= 2 Via2 spaced < 0.30 um or >= 4 Via2 spaced < 0.60 um
2285 0 VIA3.X.1: Metal3 must connect to Metal4 with >= 2 Via3 spaced < 0.30 um or >= 4 Via3 spaced < 0.60 um
2305 0 VIA4.X.1: Metal4 must connect to Metal5 with >= 2 Via4 spaced < 0.30 um or >= 4 Via4 spaced < 0.60 um
2325 0 VIA5.X.1: Metal5 must connect to Metal6 with >= 2 Via5 spaced < 0.30 um or >= 4 Via5 spaced < 0.60 um
2345 0 VIA6.X.1: Metal6 must connect to Metal7 with >= 2 Via6 spaced < 0.30 um or >= 4 Via6 spaced < 0.60 um
2365 0 VIA7.X.1: Metal7 must connect to Metal8 with >= 2 Via7 spaced < 0.30 um or >= 4 Via7 spaced < 0.60 um
2385 0 VIA8.X.1: Metal8 must connect to Metal9 with >= 2 Via8 spaced < 0.30 um or >= 4 Via8 spaced < 0.60 um
2391 0 BONDPAD.B.1A: Bondpad Metal1 must have bevelled corners
2397 0 BONDPAD.B.1A: Bondpad Metal2 must have bevelled corners
2403 0 BONDPAD.B.1A: Bondpad Metal3 must have bevelled corners
2409 0 BONDPAD.B.1A: Bondpad Metal4 must have bevelled corners
2415 0 BONDPAD.B.1A: Bondpad Metal5 must have bevelled corners
2421 0 BONDPAD.B.1A: Bondpad Metal6 must have bevelled corners
2427 0 BONDPAD.B.1A: Bondpad Metal7 must have bevelled corners
2433 0 BONDPAD.B.1A: Bondpad Metal8 must have bevelled corners
2439 0 BONDPAD.B.1A: Bondpad Metal9 must have bevelled corners
2445 0 BONDPAD.B.1A: Bondpad Metal10 must have bevelled corners
2451 0 BONDPAD.B.1A: Bondpad Metal11 must have bevelled corners
2453 0 ptap_StampErrorFloat
2454 0 ptap_StampErrorMult
2455 0 ptap_StampErrorConnect
2460 0 psubstrate_StampErrorFloat
2461 0 psubstrate_StampErrorMult
2462 0 psubstrate_StampErrorConnect
2467 0 ntap_StampErrorFloat
2468 0 ntap_StampErrorMult
2469 0 ntap_StampErrorConnect
2474 0 nwell_conn_StampErrorFloat
2475 0 nwell_conn_StampErrorMult
2476 0 nwell_conn_StampErrorConnect
2481 0 nb_tap_StampErrorFloat
2482 0 nb_tap_StampErrorMult
2483 0 nb_tap_StampErrorConnect
2488 0 Nburied_StampErrorFloat
2489 0 Nburied_StampErrorMult
2490 0 Nburied_StampErrorConnect
2528 0 NBL.W.1: Minimum Nburied Width >= 0.8 um
2530 0 NBL.E.1: Minimum Nburied to Nwell enclosure >= 0.2 um
2532 0 NBL.E.1: Minimum Nburied to Nwell enclosure >= 0.2 um
2534 0 NBL.SP.1: Minimum Nburied to Nburied spacing >= 2.0 um
2536 0 NBL.SE.1: Minimum Nburied to non-related Nwell spacing >= 2.2 um
2537 0 NBL.SE.1: Minimum Nburied to non-related Nwell spacing >= 2.2 um
2540 0 NBL.SE.2: Minimum Nburied to non-related Oxide spacing >= 1.2 um
2541 0 NBL.SE.2: Minimum Nburied to non-related Oxide spacing >= 1.2 um
2546 0 NBL.SE.3: Minimum Nwell ring (on Nburied) to P+ Active spacing >= 0.09 um
2548 0 NBL.SE.3: Minimum Nwell ring (on Nburied) to P+ Active spacing >= 0.09 um
2552 0 NBL.SE.4: Minimum Nwell ring (on Nburied) to N+ Active spacing >= 0.09 um
2554 0 NBL.SE.4: Minimum Nwell ring (on Nburied) to N+ Active spacing >= 0.09 um
2556 0 NW.SP.1: Minimum Nwell spacing to Nwell (same potential) >= 0.3 um
2558 0 NW.SP.1: Minimum Nwell spacing to Nwell (same potential) >= 0.3 um
2561 0 NW.SP.2: Minimum Nwell spacing to Nwell (different potential) >= 0.6 um
2562 0 NW.SP.2: Minimum Nwell spacing to Nwell (different potential) >= 0.6 um
2564 0 NW.SP.2: Minimum Nwell spacing to Nwell (different potential) >= 0.6 um
2565 0 NW.W.1: Minimum Nwell Width >= 0.3 um
2567 0 NW.SP.2: Minimum Nwell spacing to Nwell (different potential) >= 0.6 um
2570 0 NW.SE.2: Minimum Nwell spacing to P+ Active Area >= 0.16 um
2571 0 NW.SE.2: Minimum Nwell spacing to P+ Active Area >= 0.16 um
2575 0 NW.SE.1: Minimum Nwell spacing to N+ Active Area >= 0.16 um
2576 0 NW.SE.1: Minimum Nwell spacing to N+ Active Area >= 0.16 um
2581 0 NW.SE.3: Minimum Nwell spacing to N+ 1.8V Active Area >= 0.24 um
2582 0 NW.SE.3: Minimum Nwell spacing to N+ 1.8V Active Area >= 0.24 um
2587 0 NW.SE.4: Minimum Nwell spacing to P+ 1.8V Active Area >= 0.24 um
2588 0 NW.SE.4: Minimum Nwell spacing to P+ 1.8V Active Area >= 0.24 um
2592 0 NW.E.1: Minimum Nwell enclosure of N+ Active Area >= 0.06 um
2594 0 NW.E.1: Minimum Nwell enclosure of N+ Active Area >= 0.06 um
2595 0 NW.E.2: Minimum Nwell enclosure of P+ Active Area >= 0.06 um
2597 0 NW.E.2: Minimum Nwell enclosure of P+ Active Area >= 0.06 um
2598 0 NW.E.3: Minimum Nwell enclosure of N+ 1.8V Active Area >= 0.24 um
2600 0 NW.E.3: Minimum Nwell enclosure of N+ 1.8V Active Area >= 0.24 um
2601 0 NW.E.4: Minimum Nwell enclosure of P+ 1.8V Active Area >= 0.24 um
2603 0 NW.E.4: Minimum Nwell enclosure of P+ 1.8V Active Area >= 0.24 um
2604 0 NW.A.1: Minimum Nwell area >= 0.18 um
2605 0 NW.EA.1: Minimum Nwell enclosed area >= 0.18 um
2606 0 NWR.SE.1: Minimum Resist Protect Oxide to Nwell spacing >= 0.16 um
2608 0 NWR.E.1: Minimum Active Area to Nwell (in resistor) enclosure >= 0.6 um
2610 0 NWR.E.2: Minimum salicided Nwell to Contact enclosure >= 0.16 um
2612 0 NWR.E.2: Minimum salicided Nwell to Contact enclosure >= 0.16 um
2613 0 NWR.X.1: Thick Oxide is NOT allowed over Nwell resistor
2618 0 NWR.O.1: Minimum N+ Implant to Resist Protect Oxide overlap >= 0.22 um
2619 0 OXIDE.W.1: Minimum Active Area width >= 0.05 um
2624 0 OXIDE.W.2.1.1: Minimum 1.1V N-channel gate width >= 0.12 um
2628 0 OXIDE.W.2.1.2: Minimum 1.8V N-channel gate width >= 0.32 um
2633 0 OXIDE.W.2.2.1: Minimum 1.1V P-channel gate width >= 0.12 um
2637 0 OXIDE.W.2.2.2: Minimum 1.8V P-channel gate width >= 0.32 um
2639 0 OXIDE.W.3: Minimum Active Area bent 45 degress width >= 0.06 um
2641 0 OXIDE.SP.1: Minimum N+ Active Area to N+ Active Area spacing >= 0.08 um
2643 0 OXIDE.SP.2: Minimum P+ Active Area to P+ Active Area spacing >= 0.08 um
2648 0 OXIDE.SP.3: Minimum N+ Active Area to P+ Active Area spacing >= 0.1 um
2649 0 OXIDE.SE.1: Minimum Active Area to Thick Active Area spacing >= 0.18 um
2650 0 OXIDE.SP.4: Minimum Active Area bent 45 degress to Active Area spacing >= 0.1 um
2651 0 OXIDE.A.1: Minimum area for Active Area >= 0.035 um
2655 0 OXIDE.EA.1: Minimum Active Area enclosed area >= 0.04 um
2659 0 OXIDE.X.1: Oxide must be covered by N+ Implant or Nzvt or Salicide Block
2662 0 OXIDER.SE.2: Minimum Active Resistor to N+ or P+ Implant spacing >= 0.16 um
2663 0 OXIDER.SE.2: Minimum Active Resistor to N+ or P+ Implant spacing >= 0.16 um
2666 0 OXIDER.SE.2: Minimum Active Resistor to N+ or P+ Implant spacing >= 0.16 um
2667 0 OXIDER.SE.2: Minimum Active Resistor to N+ or P+ Implant spacing >= 0.16 um
2669 0 OXIDER.E.1: Minimum Salicide Block to Active Resistor enclosure >= 0.12 um
2671 0 OXIDER.X.1: Oxide resistors must have N+ or P+ Implant
2672 0 OXIDETHK.W.1: Minimum Thick Active Area width >= 0.35 um
2674 0 OXIDETHK.SP.1: Minimum Thick Active Area to Thick Active Area spacing >= 0.16 um
2676 0 OXIDETHK.SP.2: Minimum Thick Active Area bent 45 degrees to Thick Active Area spacing >= 0.32 um
2678 0 OXIDETHK.SE.1: Minimum N+ 1.8V Active Area to 1.8V N+ Active Area spacing >= 0.1 um
2680 0 OXIDETHK.SE.2: Minimum P+ 1.8V Active Area to 1.8V P+ Active Area spacing >= 0.1 um
2681 0 OXIDETHK.SE.3: Minimum N+ 1.8V Active Area to 1.8V P+ Active Area spacing >= 0.12 um
2683 0 OXIDETHK.E.1: Minimum Thick Active Area to Active Area enclosure >= 0.16 um
2690 0 OXIDETHK.SE.5: Minimum Thick Active Area to 1.1V Poly gate spacing >= 0.18 um
2691 0 OXIDETHK.SE.5: Minimum Thick Active Area to 1.1V Poly gate spacing >= 0.18 um
2693 0 OXIDETHK.E.2: Minimum Thick Active Area to Thick Poly gate enclosure >= 0.18 um
2694 0 NHVT.W.1: Minimum Nhvt width >= 0.12
2696 0 NHVT.SP.1: Minimum Nhvt spacing >= 0.12
2697 0 NHVT.X.2: Nhvt is NOT allowed on Nwell
2698 0 NHVT.X.3: Nhvt is NOT allowed on P+ Oxide
2699 0 NHVT.X.4: Nhvt is NOT allowed on Nzvt
2700 0 PHVT.W.1: Minimum Phvt width >= 0.12
2702 0 PHVT.SP.1: Minimum Phvt spacing >= 0.12
2703 0 PHVT.X.2: Phvt is NOT allowed outside Nwell
2704 0 PHVT.X.3: Phvt is NOT allowed on N+ Oxide
2705 0 PHVT.X.4: Phvt is NOT allowed on Nzvt
2706 0 NLVT.W.1: Minimum Nlvt width >= 0.12
2708 0 NLVT.SP.1: Minimum Nlvt spacing >= 0.12
2709 0 NLVT.X.2: Nlvt is NOT allowed on Nwell
2710 0 NLVT.X.3: Nlvt is NOT allowed on P+ Oxide
2711 0 NLVT.X.4: Nlvt is NOT allowed on Nzvt
2712 0 PLVT.W.1: Minimum Plvt width >= 0.12
2714 0 PLVT.SP.1: Minimum Plvt spacing >= 0.12
2715 0 PLVT.X.2: Plvt is NOT allowed outside Nwell
2716 0 PLVT.X.3: Plvt is NOT allowed on N+ Oxide
2717 0 PLVT.X.4: Plvt is NOT allowed on Nzvt
2718 0 NZVT.W.1: Minimum Nzvt width >= 0.35 um
2720 0 NZVT.SP.1: Minimum Nzvt to Nzvt spacing >= 0.3 um
2723 0 NZVT.SE.1: Minimum Nzvt to Active spacing >= 0.18 um
2724 0 NZVT.SE.1: Minimum Nzvt to Active spacing >= 0.18 um
2725 0 NZVT.SE.2: Minimum Nzvt to Nwell spacing >= 0.6 um
2726 0 NZVT.SE.2: Minimum Nzvt to Nwell spacing >= 0.6 um
2729 0 NZVT.E.1: Minimum N+ Poly gate end cap to Native Active Area enclosure >= 0.1 um
2732 0 NZVT.L.1: Minimum Native device Poly gate length >= 0.30 um
2736 0 NZVT.W.2: Minimum Native device Poly gate width >= 0.50 um
2738 0 NZVT.X.3: P+ Oxide is NOT allowed in Nzvt
2741 0 POLY.W.1: Minimum 1.1V N-channel gate length >= 0.045 um
2744 0 POLY.W.2: Minimum 1.1V P-channel gate length >= 0.045 um
2748 0 POLY.W.3: Minimum 1.8V N-channel gate length >= 0.15 um
2753 0 POLY.W.4: Minimum 1.8V P-channel gate length >= 0.15 um
2756 0 POLY.W.5: Minimum Poly interconnect width >= 0.045 um
2760 0 POLY.SP.1: Minimum Poly resistor space >= 0.3 um
2762 0 POLY.SP.2: Minimum Poly gate space  >= 0.06 um
2764 0 POLY.SP.3: Minimum Poly interconnect space >= 0.06 um
2768 0 POLY.SP.4: Minimum gate space in thick active >= 0.20 um
2771 0 POLY.E.1: Minimum N-channel gate extension beyond Active Area >= 0.1 um
2773 0 POLY.E.1: Minimum N-channel gate extension beyond Active Area >= 0.1 um
2776 0 POLY.E.2: Minimum P-channel gate extension beyond Active Area >= 0.1 um
2778 0 POLY.E.2: Minimum P-channel gate extension beyond Active Area >= 0.1 um
2779 0 POLY.SE.1_POLY.SE.2: Minimum Poly interconnect to related Active Area space >= 0.05 um
2781 0 POLY.E.3: Minimum Active Area (source/drain) to gate enclosure >= 0.1 um
2783 0 POLY.W.6: Minimum bent Poly width >= 0.1 um
2785 0 POLY.SP.5: Minimum bent Poly space >= 0.1 um
2786 0 POLY.X.1: Poly gate cannot have bends
2787 0 POLY.X.2: Poly resistor cannot have bends
4199 0 POLY.LN.1  Maximum Poly length [Poly width is <= 0.16 um] between two contacts as well as between one contact and the Poly line end <= 20um  
4200 0 POLY.A.1: Minimum area for Poly interconnect >= 0.02 um
4204 0 POLY.EA.1: Minimum enclosed area for Poly interconnect >= 0.05 um
4206 0 POLYR.E.1: Minimum Salicide Block to Poly resistor enclosure >= 0.14 um
4208 0 POLYR.E.2: Minimum N+ Implant to Poly used in resistor enclosure >= 0.07 um
4210 0 POLYR.E.2: Minimum N+ Implant to Poly used in resistor enclosure >= 0.07 um
4212 0 POLYR.E.3: Minimum P+ Implant to Poly used in resistor enclosure >= 0.07 um
4214 0 POLYR.E.3: Minimum P+ Implant to Poly used in resistor enclosure >= 0.07 um
4216 0 POLYR.SE.2: Minimum Poly resistor to other Implant spacing >= 0.15 um
4217 0 POLYR.SE.2: Minimum Poly resistor to other Implant spacing >= 0.15 um
4218 0 POLYR.SE.2: Minimum Poly resistor to other Implant spacing >= 0.15 um
4219 0 POLYR.SE.2: Minimum Poly resistor to other Implant spacing >= 0.15 um
4221 0 POLYR.SE.2: Minimum Poly resistor to other Implant spacing >= 0.15 um
4222 0 POLYR.SE.2: Minimum Poly resistor to other Implant spacing >= 0.15 um
4223 0 POLYR.X.1: Poly resistors must have N+ or P+ Implant
4224 0 NIMP.W.1: Minimum N+ Implant width >= 0.12 um
4226 0 NIMP.SP.1: Minimum N+ Implant space >= 0.12 um
4229 0 NIMP.E.1: Minimum N+ Implant to Active Area enclosure >= 0.07 um
4230 0 NIMP.O.1: Minimum N+ Implant to Active Area overlap >= 0.08 um
4238 0 NIMP.SE.1: Minimum N+ Implant to P+ Active Area (inside Nwell) spacing >= 0.08 um
4239 0 NIMP.SE.1: Minimum N+ Implant to P+ Active Area (inside Nwell) spacing >= 0.08 um
4242 0 NIMP.E.2: Minimum N+ Implant to Active Area (Nwell tie) enclosure >= 0.01 um
4246 0 NIMP.E.3: Minimum N+ Implant to gate side enclosure >= 0.1 um
4252 0 NIMP.E.4: Minimum N+ Implant to gate (endcap) enclosure >= 0.1 um
4254 0 NIMP.E.4: Minimum N+ Implant to gate (endcap) enclosure >= 0.1 um
4263 0 NIMP.SE.2: Minimum N+ Implant to P+ Active Area (substrate tie) spacing >= 0.02 um
4264 0 NIMP.SE.2: Minimum N+ Implant to P+ Active Area (substrate tie) spacing >= 0.02 um
4265 0 NIMP.A.1: Minimum area for N+ Implant >= 0.018 um
4269 0 NIMP.EA.1: Minimum N+ Implant ring enclosed area  >= 0.04 um
4272 0 NIMP.SE.3: Minimum N+ Implant to P+ gate side (butted Implant) spacing >= 0.1 um
4273 0 NIMP.SE.3: Minimum N+ Implant to P+ gate side (butted Implant) spacing >= 0.1 um
4274 0 NIMP.X.1: Nimp is NOT allowed over Pimp
4275 0 PIMP.W.1: Minimum P+ Implant width >= 0.12 um
4277 0 PIMP.SP.1: Minimum P+ Implant space >= 0.12 um
4279 0 PIMP.E.1: Minimum P+ Implant to Active Area enclosure >= 0.07 um
4280 0 PIMP.O.1: Minimum P+ Implant to Active Area overlap >= 0.08 um
4288 0 PIMP.SE.1: Minimum P+ Implant to N+ Active Area (outside Nwell) spacing >= 0.08 um
4289 0 PIMP.SE.1: Minimum P+ Implant to N+ Active Area (outside Nwell) spacing >= 0.08 um
4291 0 PIMP.E.2: Minimum P+ Implant to Active Area (substrate tie) enclosure >= 0.01 um
4295 0 PIMP.E.3: Minimum P+ Implant to gate side enclosure >= 0.1 um
4298 0 PIMP.E.4: Minimum P+ Implant to gate (endcap) enclosure >= 0.1 um
4300 0 PIMP.E.4: Minimum P+ Implant to gate (endcap) enclosure >= 0.1 um
4309 0 PIMP.SE.2: Minimum P+ Implant to N+ Active Area (Nwell tie) spacing >= 0.02 um
4310 0 PIMP.SE.2: Minimum P+ Implant to N+ Active Area (Nwell tie) spacing >= 0.02 um
4311 0 PIMP.A.1: Minimum area for P+ Implant >= 0.018 um
4315 0 PIMP.EA.1: Minimum P+ Implant ring enclosed area  >= 0.04 um
4318 0 PIMP.SE.3: Minimum P+ Implant to N+ gate side (butted Implant) spacing >= 0.1 um
4319 0 PIMP.SE.3: Minimum P+ Implant to N+ gate side (butted Implant) spacing >= 0.1 um
4321 0 CONT.W.1: Maximum and minimum Contact width/length == 0.06 um
4323 0 CONT.SP.1: Minimum Contact to Contact spacing >= 0.06 um
4325 0 CONT.SP.2: Space to three adjacent Contacts ( < 0.10um apart) >= 0.08 um
4328 0 CONT.SE.1: Minimum Contact on Active Area to gate spacing >= 0.05 um
4329 0 CONT.SE.1: Minimum Contact on Active Area to gate spacing >= 0.05 um
4333 0 CONT.SE.2: Minimum Contact on 1.8V Active Area to gate spacing >= 0.06 um
4334 0 CONT.SE.2: Minimum Contact on 1.8V Active Area to gate spacing >= 0.06 um
4336 0 CONT.SE.3: Minimum gate Contact on Active Area spacing >= 0.06 um
4337 0 CONT.SE.3: Minimum gate Contact on Active Area spacing >= 0.06 um
4342 0 CONT.SE.4: Minimum 1.8V gate Contact on Active Area spacing >= 0.07 um
4343 0 CONT.SE.4: Minimum 1.8V gate Contact on Active Area spacing >= 0.07 um
4345 0 CONT.E.1: Minimum Active Area to Contact enclosure >= 0.03 um
4347 0 CONT.E.1: Minimum Active Area to Contact enclosure >= 0.03 um
4349 0 CONT.E.2: Minimum Poly to Contact enclosure >= 0.02 um
4351 0 CONT.E.2: Minimum Poly to Contact enclosure >= 0.02 um
4354 0 CONT.E.3: Minimum Poly to Contact enclosure on at least two opposite sides >= 0.03 um
4357 0 CONT.E.4: Minimum N+/P+ Implant on Active Area to Contact enclosure >= 0.03 um
4359 0 CONT.E.4: Minimum N+/P+ Implant on Active Area to Contact enclosure >= 0.03 um
4362 0 CONT.E.4: Minimum N+/P+ Implant on Active Area to Contact enclosure >= 0.03 um
4364 0 CONT.E.4: Minimum N+/P+ Implant on Active Area to Contact enclosure >= 0.03 um
4365 0 CONT.X.1: Cont on gate is NOT allowed
4368 0 CONT.X.2: Nimp edge is NOT allowed on Oxide Cont
4371 0 CONT.X.2: Pimp edge is NOT allowed on Oxide Cont
4372 0 CONT.X.3: CONT must be covered by Oxide or Poly
4373 0 SIPROT.W.1: Minimum Salicide Block width >= 0.22 um
4375 0 SIPROT.SP.1: Minimum Salicide Block space >= 0.22 um
4378 0 SIPROT.SE.1: Minimum Salicide Block to Contact spacing >= 0.12 um
4379 0 SIPROT.SE.1: Minimum Salicide Block to Contact spacing >= 0.12 um
4380 0 SIPROT.SE.2: Minimum Salicide Block to unrelated Active Area spacing >= 0.12 um
4384 0 SIPROT.SE.3: Minimum Salicide Block to gate spacing >= 0.22 um
4385 0 SIPROT.SE.3: Minimum Salicide Block to gate spacing >= 0.22 um
4387 0 SIPROT.E.2: Minimum Active Area to Salicide Block enclosure >= 0.12 um
4391 0 SIPROT.E.1: Minimum Salicide Block to Active Area enclosure >= 0.12 um
4393 0 SIPROT.E.3: Minimum Salicide Block to Poly (on field) enclosure >= 0.14 um
4394 0 SIPROT.A.1: Minimum Salicide Block area >= 0.6 um
4395 0 SIPROT.SE.4: Minimum Salicide Block to Poly (on field) spacing >= 0.18 um
4399 0 SIPROT.EA.1: Minimum Salicide Block enclosed area >= 0.6 um
4400 0 METAL2.E.1: Metal2 to Via1 enclosure must be >= 0.005 um
4402 0 METAL2.E.1: Metal2 to Via1 enclosure must be >= 0.005 um
4406 0 METAL2.E.2: Metal2 to Via1 enclosure on opposite sides must be >= 0.03 um
4407 0 METAL3.E.1: Metal3 to Via2 enclosure must be >= 0.005 um
4409 0 METAL3.E.1: Metal3 to Via2 enclosure must be >= 0.005 um
4413 0 METAL3.E.2: Metal3 to Via2 enclosure on opposite sides must be >= 0.03 um
4414 0 METAL4.E.1: Metal4 to Via3 enclosure must be >= 0.005 um
4416 0 METAL4.E.1: Metal4 to Via3 enclosure must be >= 0.005 um
4420 0 METAL4.E.2: Metal4 to Via3 enclosure on opposite sides must be >= 0.03 um
4421 0 METAL5.E.1: Metal5 to Via4 enclosure must be >= 0.005 um
4423 0 METAL5.E.1: Metal5 to Via4 enclosure must be >= 0.005 um
4427 0 METAL5.E.2: Metal5 to Via4 enclosure on opposite sides must be >= 0.03 um
4428 0 METAL6.E.1: Metal6 to Via5 enclosure must be >= 0.005 um
4430 0 METAL6.E.1: Metal6 to Via5 enclosure must be >= 0.005 um
4434 0 METAL6.E.2: Metal6 to Via5 enclosure on opposite sides must be >= 0.03 um
4435 0 METAL7.E.1: Metal7 to Via6 enclosure must be >= 0.005 um
4437 0 METAL7.E.1: Metal7 to Via6 enclosure must be >= 0.005 um
4441 0 METAL7.E.2: Metal7 to Via6 enclosure on opposite sides must be >= 0.03 um
4442 0 METAL8.E.1: Metal8 to Via7 enclosure must be >= 0.005 um
4444 0 METAL8.E.1: Metal8 to Via7 enclosure must be >= 0.005 um
4448 0 METAL8.E.2: Metal8 to Via7 enclosure on opposite sides must be >= 0.03 um
4449 0 METAL9.E.1: Metal9 to Via8 enclosure must be >= 0.005 um
4451 0 METAL9.E.1: Metal9 to Via8 enclosure must be >= 0.005 um
4455 0 METAL9.E.2: Metal9 to Via8 enclosure on opposite sides must be >= 0.03 um
4456 0 METAL10.E.1: Metal10 to Via9 enclosure must be >= 0.03 um
4458 0 METAL10.E.1: Metal10 to Via9 enclosure must be >= 0.03 um
4462 0 METAL10.E.2: Metal10 to Via9 enclosure on opposite sides must be >= 0.05 um
4463 0 METAL11.E.1: Metal11 to Via10 enclosure must be >= 0.03 um
4465 0 METAL11.E.1: Metal11 to Via10 enclosure must be >= 0.03 um
4469 0 METAL11.E.2: Metal11 to Via10 enclosure on opposite sides must be >= 0.05 um
4470 0 METAL1.E.1: 0.00 >= 0.00 um
4474 0 METAL1.E.2: 0.03 >= 0.03 um
4475 0 METAL1.W.1: Metal1 width must be >= 0.06 um
4476 0 METAL2.W.1: Metal2 width must be >= 0.08 um
4477 0 METAL3.W.1: Metal3 width must be >= 0.08 um
4478 0 METAL4.W.1: Metal4 width must be >= 0.08 um
4479 0 METAL5.W.1: Metal5 width must be >= 0.08 um
4480 0 METAL6.W.1: Metal6 width must be >= 0.08 um
4481 0 METAL7.W.1: Metal7 width must be >= 0.08 um
4482 0 METAL8.W.1: Metal8 width must be >= 0.08 um
4483 0 METAL9.W.1: Metal9 width must be >= 0.08 um
4484 0 METAL10.W.1: Metal10 width must be >= 0.22 um
4485 0 METAL11.W.1: Metal11 width must be >= 0.22 um
4489 0 METAL1.W.2: Metal1 width must be <= 6.0 um
4493 0 METAL2.W.2: Metal2 width must be <= 6.0 um
4497 0 METAL3.W.2: Metal3 width must be <= 6.0 um
4501 0 METAL4.W.2: Metal4 width must be <= 6.0 um
4505 0 METAL5.W.2: Metal5 width must be <= 6.0 um
4509 0 METAL6.W.2: Metal6 width must be <= 6.0 um
4513 0 METAL7.W.2: Metal7 width must be <= 6.0 um
4517 0 METAL8.W.2: Metal8 width must be <= 6.0 um
4519 0 METAL9.W.2: Metal9 width must be <= 6.0 um
4521 0 METAL10.W.2: Metal10 width must be <= 6.0 um
4523 0 METAL11.W.2: Metal11 width must be <= 6.0 um
4525 0 METAL1.SP.1.1: Metal1 to Metal1 spacing must be >= 0.06 um
4527 0 METAL2.SP.1.1: Metal2 to Metal2 spacing must be >= 0.07 um
4529 0 METAL3.SP.1.1: Metal3 to Metal3 spacing must be >= 0.07 um
4531 0 METAL4.SP.1.1: Metal4 to Metal4 spacing must be >= 0.07 um
4533 0 METAL5.SP.1.1: Metal5 to Metal5 spacing must be >= 0.07 um
4535 0 METAL6.SP.1.1: Metal6 to Metal6 spacing must be >= 0.07 um
4537 0 METAL7.SP.1.1: Metal7 to Metal7 spacing must be >= 0.07 um
4539 0 METAL8.SP.1.1: Metal8 to Metal8 spacing must be >= 0.07 um
4541 0 METAL9.SP.1.1: Metal9 to Metal9 spacing must be >= 0.07 um
4543 0 METAL10.SP.1.1: Metal10 to Metal10 spacing must be >= 0.20 um
4545 0 METAL11.SP.1.1: Metal11 to Metal11 spacing must be >= 0.20 um
4552 0 METAL1.SP.1.2: Metal1 to Metal1 spacing must be >= 0.1 um
4559 0 METAL2.SP.1.2: Metal2 to Metal2 spacing must be >= 0.15 um
4566 0 METAL3.SP.1.2: Metal3 to Metal3 spacing must be >= 0.15 um
4573 0 METAL4.SP.1.2: Metal4 to Metal4 spacing must be >= 0.15 um
4580 0 METAL5.SP.1.2: Metal5 to Metal5 spacing must be >= 0.15 um
4587 0 METAL6.SP.1.2: Metal6 to Metal6 spacing must be >= 0.15 um
4594 0 METAL7.SP.1.2: Metal7 to Metal7 spacing must be >= 0.15 um
4601 0 METAL8.SP.1.2: Metal8 to Metal8 spacing must be >= 0.15 um
4608 0 METAL9.SP.1.2: Metal9 to Metal9 spacing must be >= 0.15 um
4614 0 METAL1.SP.1.3: Metal1 to Metal1 spacing must be >= 0.25 um
4620 0 METAL2.SP.1.3: Metal2 to Metal2 spacing must be >= 0.25 um
4626 0 METAL3.SP.1.3: Metal3 to Metal3 spacing must be >= 0.25 um
4632 0 METAL4.SP.1.3: Metal4 to Metal4 spacing must be >= 0.25 um
4638 0 METAL5.SP.1.3: Metal5 to Metal5 spacing must be >= 0.25 um
4644 0 METAL6.SP.1.3: Metal6 to Metal6 spacing must be >= 0.25 um
4650 0 METAL7.SP.1.3: Metal7 to Metal7 spacing must be >= 0.25 um
4656 0 METAL8.SP.1.3: Metal8 to Metal8 spacing must be >= 0.25 um
4662 0 METAL9.SP.1.3: Metal9 to Metal9 spacing must be >= 0.25 um
4669 0 METAL10.SP.1.2: Metal10 to Metal10 spacing must be >= 0.35 um
4676 0 METAL11.SP.1.2: Metal11 to Metal11 spacing must be >= 0.35 um
4682 0 METAL1.SP.1.4: Metal1 to Metal1 spacing must be >= 0.45 um
4688 0 METAL2.SP.1.4: Metal2 to Metal2 spacing must be >= 0.45 um
4694 0 METAL3.SP.1.4: Metal3 to Metal3 spacing must be >= 0.45 um
4700 0 METAL4.SP.1.4: Metal4 to Metal4 spacing must be >= 0.45 um
4706 0 METAL5.SP.1.4: Metal5 to Metal5 spacing must be >= 0.45 um
4712 0 METAL6.SP.1.4: Metal6 to Metal6 spacing must be >= 0.45 um
4718 0 METAL7.SP.1.4: Metal7 to Metal7 spacing must be >= 0.45 um
4724 0 METAL8.SP.1.4: Metal8 to Metal8 spacing must be >= 0.45 um
4730 0 METAL9.SP.1.4: Metal9 to Metal9 spacing must be >= 0.45 um
4736 0 METAL10.SP.1.3: Metal10 to Metal10 spacing must be >= 0.45 um
4742 0 METAL11.SP.1.3: Metal11 to Metal11 spacing must be >= 0.45 um
4748 0 METAL1.SP.1.5: Metal1 to Metal1 spacing must be >= 0.75 um
4754 0 METAL2.SP.1.5: Metal2 to Metal2 spacing must be >= 0.75 um
4760 0 METAL3.SP.1.5: Metal3 to Metal3 spacing must be >= 0.75 um
4766 0 METAL4.SP.1.5: Metal4 to Metal4 spacing must be >= 0.75 um
4772 0 METAL5.SP.1.5: Metal5 to Metal5 spacing must be >= 0.75 um
4778 0 METAL6.SP.1.5: Metal6 to Metal6 spacing must be >= 0.75 um
4784 0 METAL7.SP.1.5: Metal7 to Metal7 spacing must be >= 0.75 um
4790 0 METAL8.SP.1.5: Metal8 to Metal8 spacing must be >= 0.75 um
4796 0 METAL9.SP.1.5: Metal9 to Metal9 spacing must be >= 0.75 um
4802 0 METAL10.SP.1.4: Metal10 to Metal10 spacing must be >= 0.75 um
4808 0 METAL11.SP.1.4: Metal11 to Metal11 spacing must be >= 0.75 um
4812 0 METAL1.SP.1.6: Metal1 to Metal1 spacing must be >= 1.25 um
4816 0 METAL2.SP.1.6: Metal2 to Metal2 spacing must be >= 1.25 um
4820 0 METAL3.SP.1.6: Metal3 to Metal3 spacing must be >= 1.25 um
4824 0 METAL4.SP.1.6: Metal4 to Metal4 spacing must be >= 1.25 um
4828 0 METAL5.SP.1.6: Metal5 to Metal5 spacing must be >= 1.25 um
4832 0 METAL6.SP.1.6: Metal6 to Metal6 spacing must be >= 1.25 um
4836 0 METAL7.SP.1.6: Metal7 to Metal7 spacing must be >= 1.25 um
4840 0 METAL8.SP.1.6: Metal8 to Metal8 spacing must be >= 1.25 um
4844 0 METAL9.SP.1.6: Metal9 to Metal9 spacing must be >= 1.25 um
4848 0 METAL10.SP.1.5: Metal10 to Metal10 spacing must be >= 1.25 um
4852 0 METAL11.SP.1.5: Metal11 to Metal11 spacing must be >= 1.25 um
4854 0 METAL1.L.1: Metal1 non-90 degree segments must be >= 0.1 um
4856 0 METAL2.L.1: Metal2 non-90 degree segments must be >= 0.1 um
4858 0 METAL3.L.1: Metal3 non-90 degree segments must be >= 0.1 um
4860 0 METAL4.L.1: Metal4 non-90 degree segments must be >= 0.1 um
4862 0 METAL5.L.1: Metal5 non-90 degree segments must be >= 0.1 um
4864 0 METAL6.L.1: Metal6 non-90 degree segments must be >= 0.1 um
4866 0 METAL7.L.1: Metal7 non-90 degree segments must be >= 0.1 um
4868 0 METAL8.L.1: Metal8 non-90 degree segments must be >= 0.1 um
4870 0 METAL9.L.1: Metal9 non-90 degree segments must be >= 0.1 um
4871 0 METAL1.SP.2: Metal1 to bent Metal1 spacing must be >= 0.1 um
4872 0 METAL1.W.3: Bent Metal1 (45 degree angle) width must be >= 0.07
4873 0 METAL2.SP.2: Metal2 to bent Metal2 spacing must be >= 0.1 um
4874 0 METAL2.W.3: Bent Metal2 (45 degree angle) width must be >= 0.09
4875 0 METAL3.SP.2: Metal3 to bent Metal3 spacing must be >= 0.1 um
4876 0 METAL3.W.3: Bent Metal3 (45 degree angle) width must be >= 0.09
4877 0 METAL4.SP.2: Metal4 to bent Metal4 spacing must be >= 0.1 um
4878 0 METAL4.W.3: Bent Metal4 (45 degree angle) width must be >= 0.09
4879 0 METAL5.SP.2: Metal5 to bent Metal5 spacing must be >= 0.1 um
4880 0 METAL5.W.3: Bent Metal5 (45 degree angle) width must be >= 0.09
4881 0 METAL6.SP.2: Metal6 to bent Metal6 spacing must be >= 0.1 um
4882 0 METAL6.W.3: Bent Metal6 (45 degree angle) width must be >= 0.09
4883 0 METAL7.SP.2: Metal7 to bent Metal7 spacing must be >= 0.1 um
4884 0 METAL7.W.3: Bent Metal7 (45 degree angle) width must be >= 0.09
4885 0 METAL8.SP.2: Metal8 to bent Metal8 spacing must be >= 0.1 um
4886 0 METAL8.W.3: Bent Metal8 (45 degree angle) width must be >= 0.09
4887 0 METAL9.SP.2: Metal9 to bent Metal9 spacing must be >= 0.1 um
4888 0 METAL9.W.3: Bent Metal9 (45 degree angle) width must be >= 0.09
4889 0 METAL1.SP.3: Min End of Line Spacing >= 0.08
4890 0 METAL2.SP.3: Min End of Line Spacing >= 0.08
4891 0 METAL3.SP.3: Min End of Line Spacing >= 0.08
4892 0 METAL4.SP.3: Min End of Line Spacing >= 0.08
4893 0 METAL5.SP.3: Min End of Line Spacing >= 0.08
4894 0 METAL6.SP.3: Min End of Line Spacing >= 0.08
4895 0 METAL7.SP.3: Min End of Line Spacing >= 0.08
4896 0 METAL8.SP.3: Min End of Line Spacing >= 0.08
4897 0 METAL9.SP.3: Min End of Line Spacing >= 0.08
4898 0 METAL1.A.1: Metal1 area must be >= 0.02 um
4899 0 METAL2.A.1: Metal2 area must be >= 0.02 um
4900 0 METAL3.A.1: Metal3 area must be >= 0.02 um
4901 0 METAL4.A.1: Metal4 area must be >= 0.02 um
4902 0 METAL5.A.1: Metal5 area must be >= 0.02 um
4903 0 METAL6.A.1: Metal6 area must be >= 0.02 um
4904 0 METAL7.A.1: Metal7 area must be >= 0.02 um
4905 0 METAL8.A.1: Metal8 area must be >= 0.02 um
4906 0 METAL9.A.1: Metal9 area must be >= 0.02 um
4907 0 METAL10.A.1: Metal10 area must be >= 0.10 um
4908 0 METAL11.A.1: Metal11 area must be >= 0.10 um
4912 0 METAL1.EA.1: Metal1 enclosed area must be >= 0.05 um
4916 0 METAL2.EA.1: Metal2 enclosed area must be >= 0.05 um
4920 0 METAL3.EA.1: Metal3 enclosed area must be >= 0.05 um
4924 0 METAL4.EA.1: Metal4 enclosed area must be >= 0.05 um
4928 0 METAL5.EA.1: Metal5 enclosed area must be >= 0.05 um
4932 0 METAL6.EA.1: Metal6 enclosed area must be >= 0.05 um
4936 0 METAL7.EA.1: Metal7 enclosed area must be >= 0.05 um
4940 0 METAL8.EA.1: Metal8 enclosed area must be >= 0.05 um
4944 0 METAL9.EA.1: Metal9 enclosed area must be >= 0.05 um
4948 0 METAL10.EA.1: Metal10 enclosed area must be >= 0.05 um
4952 0 METAL11.EA.1: Metal11 enclosed area must be >= 0.05 um
4954 0 CMET.S.1: Minimum space of CapMetal >= 1.0 um
4955 0 CMET.W.1: Minimum width of CapMetal >= 1.0 um
4957 0 CMET.E.1: Minimum Metal 1 overlap of Via 10 on CapMetal >= 0.05 um
4959 0 CMET.E.1: Minimum Metal 1 overlap of Via 10 on CapMetal >= 0.05 um
4961 0 CMET.E.2: Minimum CapMetal overlap of Via 10 >= 0.15 um
4963 0 CMET.E.2: Minimum CapMetal overlap of Via 10 >= 0.15 um
4965 0 CMET.E.4: Minimum Metal 10 overlap of CapMetal >= 0.2 um
4967 0 CMET.E.4: Minimum Metal 10 overlap of CapMetal >= 0.2 um
4969 0 CMET.E.3: Minimum CapMetal extension over Metal 11 >= 0.1 um
4971 0 VIA1.W.1: Via1 shapes must be 0.07x0.07 rectangles
4973 0 VIA1.SP.1: Via1 to Via1 spacing must be >= 0.07 um
4975 0 VIA2.W.1: Via2 shapes must be 0.07x0.07 rectangles
4977 0 VIA2.SP.1: Via2 to Via2 spacing must be >= 0.07 um
4979 0 VIA3.W.1: Via3 shapes must be 0.07x0.07 rectangles
4981 0 VIA3.SP.1: Via3 to Via3 spacing must be >= 0.07 um
4983 0 VIA4.W.1: Via4 shapes must be 0.07x0.07 rectangles
4985 0 VIA4.SP.1: Via4 to Via4 spacing must be >= 0.07 um
4987 0 VIA5.W.1: Via5 shapes must be 0.07x0.07 rectangles
4989 0 VIA5.SP.1: Via5 to Via5 spacing must be >= 0.07 um
4991 0 VIA6.W.1: Via6 shapes must be 0.07x0.07 rectangles
4993 0 VIA6.SP.1: Via6 to Via6 spacing must be >= 0.07 um
4995 0 VIA7.W.1: Via7 shapes must be 0.07x0.07 rectangles
4997 0 VIA7.SP.1: Via7 to Via7 spacing must be >= 0.07 um
4999 0 VIA8.W.1: Via8 shapes must be 0.07x0.07 rectangles
5001 0 VIA8.SP.1: Via8 to Via8 spacing must be >= 0.07 um
5003 0 VIA9.W.1: Via9 shapes must be 0.18x0.18 rectangles
5005 0 VIA9.SP.1: Via9 to Via9 spacing must be >= 0.18 um
5007 0 VIA10.W.1: Via10 shapes must be 0.18x0.18 rectangles
5009 0 VIA10.SP.1: Via10 to Via10 spacing must be >= 0.18 um
5010 0 VIA1.E.1: Metal1 to Via1 enclosure must be >= 0.005 um
5012 0 VIA1.E.1: Metal1 to Via1 enclosure must be >= 0.005 um
5016 0 VIA1.E.2: Metal1 to Via1 enclosure on opposite sides must be >= 0.03 um
5017 0 VIA2.E.1: Metal2 to Via2 enclosure must be >= 0.005 um
5019 0 VIA2.E.1: Metal2 to Via2 enclosure must be >= 0.005 um
5023 0 VIA2.E.2: Metal2 to Via2 enclosure on opposite sides must be >= 0.03 um
5024 0 VIA3.E.1: Metal3 to Via3 enclosure must be >= 0.005 um
5026 0 VIA3.E.1: Metal3 to Via3 enclosure must be >= 0.005 um
5030 0 VIA3.E.2: Metal3 to Via3 enclosure on opposite sides must be >= 0.03 um
5031 0 VIA4.E.1: Metal4 to Via4 enclosure must be >= 0.005 um
5033 0 VIA4.E.1: Metal4 to Via4 enclosure must be >= 0.005 um
5037 0 VIA4.E.2: Metal4 to Via4 enclosure on opposite sides must be >= 0.03 um
5038 0 VIA5.E.1: Metal5 to Via5 enclosure must be >= 0.005 um
5040 0 VIA5.E.1: Metal5 to Via5 enclosure must be >= 0.005 um
5044 0 VIA5.E.2: Metal5 to Via5 enclosure on opposite sides must be >= 0.03 um
5045 0 VIA6.E.1: Metal6 to Via6 enclosure must be >= 0.005 um
5047 0 VIA6.E.1: Metal6 to Via6 enclosure must be >= 0.005 um
5051 0 VIA6.E.2: Metal6 to Via6 enclosure on opposite sides must be >= 0.03 um
5052 0 VIA7.E.1: Metal7 to Via7 enclosure must be >= 0.005 um
5054 0 VIA7.E.1: Metal7 to Via7 enclosure must be >= 0.005 um
5058 0 VIA7.E.2: Metal7 to Via7 enclosure on opposite sides must be >= 0.03 um
5059 0 VIA8.E.1: Metal8 to Via8 enclosure must be >= 0.005 um
5061 0 VIA8.E.1: Metal8 to Via8 enclosure must be >= 0.005 um
5065 0 VIA8.E.2: Metal8 to Via8 enclosure on opposite sides must be >= 0.03 um
5066 0 VIA9.E.1: Metal9 to Via9 enclosure must be >= 0.015 um
5068 0 VIA9.E.1: Metal9 to Via9 enclosure must be >= 0.015 um
5072 0 VIA9.E.2: Metal9 to Via9 enclosure on opposite sides must be >= 0.04 um
5073 0 VIA10.E.1: Metal10 to Via10 enclosure must be >= 0.015 um
5075 0 VIA10.E.1: Metal10 to Via10 enclosure must be >= 0.015 um
5079 0 VIA10.E.2: Metal10 to Via10 enclosure on opposite sides must be >= 0.04 um
5296 0 LATCHUP.1: The maximum distance from any point in a P+ source/drain Active Area to the nearest Nwell pick-up in the same Nwell >= 20.0 um
5895 0 LATCHUP.2: The maximum distance from any point in a N+ source/drain Active Area to the nearest Psub pick-up in the same Psub >= 20.0 um
5898 0 LATCHUP.3: Minimum I/O or ESD NMOS to PMOS spacing >= 10.0 um
5899 0 LATCHUP.3: Minimum I/O or ESD NMOS to PMOS spacing >= 10.0 um
5904 0 LATCHUP.4: Minimum I/O or ESD NMOS to PMOS spacing when not blocked by a double guardring >= 30.0 um
5908 0 LATCHUP.4: Minimum I/O or ESD NMOS to PMOS spacing when not blocked by a double guardring >= 30.0 um
5912 0 ESD.1: ESD gate width must be >= 10.0 um and <= 30.0 um
5913 0 ESD.4: N+ source should connect to Pad or Bulk
5914 0 ESD.4: P+ source should connect to Pad or Nwell
5915 0 ESD.5: NMOS I/O and ESD devices must be inside P+ rings
5916 0 ESD.6: PMOS I/O and ESD devices must be inside N+ rings
5917 0 ESD.7: P+ taps can NOT butt NMOS I/O and ESD devices
5918 0 ESD.7: N+ taps can NOT butt PMOS I/O and ESD devices
5919 0 ESD.8: N+ drains must be non-salicided (except Contact area)
5920 0 ESD.8: P+ drains must be non-salicided (except Contact area)
5923 0 ESD.11: Minimum SiProt to Poly gate overlap in NMOS and PMOS drains >= 0.05 um
5925 0 ESD.12: Minimum enclosure of SiProt edge to Poly gate edge in NMOS and PMOS drains >= 0.9 um
5927 0 ESD.13: Minimum SiProt to Oxide overlap in NMOS and PMOS I/O drains >= 0.9 um
5931 0 ESD.14: Exact gate length of NMOS and PMOS in I/O buffers and in Vdd to Vss ESD protection == 0.2 um
5935 0 ESD.15: Minimu Poly gate to Contact spacing in NMOS and PMOS in I/O buffers and in Vdd to Vss ESD protection >= 0.12 um
5936 0 ESD.15: Minimu Poly gate to Contact spacing in NMOS and PMOS in I/O buffers and in Vdd to Vss ESD protection >= 0.12 um
5938 0 BONDPAD.E.1: Metal1 to Bondpad enclosure must be >= 2.0 um
5940 0 BONDPAD.E.1: Metal1 to Bondpad enclosure must be >= 2.0 um
5941 0 BONDPAD.SP.2: Bondpad Metal1 to Metal1 spacing must be >= 3.0 um
5943 0 BONDPAD.E.1: Metal2 to Bondpad enclosure must be >= 2.0 um
5945 0 BONDPAD.E.1: Metal2 to Bondpad enclosure must be >= 2.0 um
5946 0 BONDPAD.SP.2: Bondpad Metal2 to Metal2 spacing must be >= 3.0 um
5948 0 BONDPAD.E.1: Metal3 to Bondpad enclosure must be >= 2.0 um
5950 0 BONDPAD.E.1: Metal3 to Bondpad enclosure must be >= 2.0 um
5951 0 BONDPAD.SP.2: Bondpad Metal3 to Metal3 spacing must be >= 3.0 um
5953 0 BONDPAD.E.1: Metal4 to Bondpad enclosure must be >= 2.0 um
5955 0 BONDPAD.E.1: Metal4 to Bondpad enclosure must be >= 2.0 um
5956 0 BONDPAD.SP.2: Bondpad Metal4 to Metal4 spacing must be >= 3.0 um
5958 0 BONDPAD.E.1: Metal5 to Bondpad enclosure must be >= 2.0 um
5960 0 BONDPAD.E.1: Metal5 to Bondpad enclosure must be >= 2.0 um
5961 0 BONDPAD.SP.2: Bondpad Metal5 to Metal5 spacing must be >= 3.0 um
5963 0 BONDPAD.E.1: Metal6 to Bondpad enclosure must be >= 2.0 um
5965 0 BONDPAD.E.1: Metal6 to Bondpad enclosure must be >= 2.0 um
5966 0 BONDPAD.SP.2: Bondpad Metal6 to Metal6 spacing must be >= 3.0 um
5968 0 BONDPAD.E.1: Metal7 to Bondpad enclosure must be >= 2.0 um
5970 0 BONDPAD.E.1: Metal7 to Bondpad enclosure must be >= 2.0 um
5971 0 BONDPAD.SP.2: Bondpad Metal7 to Metal7 spacing must be >= 3.0 um
5973 0 BONDPAD.E.1: Metal8 to Bondpad enclosure must be >= 2.0 um
5975 0 BONDPAD.E.1: Metal8 to Bondpad enclosure must be >= 2.0 um
5976 0 BONDPAD.SP.2: Bondpad Metal8 to Metal8 spacing must be >= 3.0 um
5978 0 BONDPAD.E.1: Metal9 to Bondpad enclosure must be >= 2.0 um
5980 0 BONDPAD.E.1: Metal9 to Bondpad enclosure must be >= 2.0 um
5981 0 BONDPAD.SP.2: Bondpad Metal9 to Metal9 spacing must be >= 3.0 um
5983 0 BONDPAD.E.1: Metal10 to Bondpad enclosure must be >= 2.0 um
5985 0 BONDPAD.E.1: Metal10 to Bondpad enclosure must be >= 2.0 um
5986 0 BONDPAD.SP.2: Bondpad Metal10 to Metal10 spacing must be >= 3.0 um
5988 0 BONDPAD.E.1: Metal11 to Bondpad enclosure must be >= 2.0 um
5990 0 BONDPAD.E.1: Metal11 to Bondpad enclosure must be >= 2.0 um
5991 0 BONDPAD.SP.2: Bondpad Metal11 to Metal11 spacing must be >= 3.0 um
5994 0 BONDPAD.W.1: Bondpad width must be >= 55.0 um
5996 0 BONDPAD.W.1: Bondpad width must be >= 55.0 um
5998 0 BONDPAD.SP.1: Bondpad to Bondpad spacing must be >= 8.0 um
6000 0 BONDPAD.B.1B: Bondpad Metal1 beveled segments must be >= 1.8 um and <= 3.2 um
6002 0 BONDPAD.B.1B: Bondpad Metal2 beveled segments must be >= 1.8 um and <= 3.2 um
6004 0 BONDPAD.B.1B: Bondpad Metal3 beveled segments must be >= 1.8 um and <= 3.2 um
6006 0 BONDPAD.B.1B: Bondpad Metal4 beveled segments must be >= 1.8 um and <= 3.2 um
6008 0 BONDPAD.B.1B: Bondpad Metal5 beveled segments must be >= 1.8 um and <= 3.2 um
6010 0 BONDPAD.B.1B: Bondpad Metal6 beveled segments must be >= 1.8 um and <= 3.2 um
6012 0 BONDPAD.B.1B: Bondpad Metal7 beveled segments must be >= 1.8 um and <= 3.2 um
6014 0 BONDPAD.B.1B: Bondpad Metal8 beveled segments must be >= 1.8 um and <= 3.2 um
6016 0 BONDPAD.B.1B: Bondpad Metal9 beveled segments must be >= 1.8 um and <= 3.2 um
6018 0 BONDPAD.B.1B: Bondpad Metal10 beveled segments must be >= 1.8 um and <= 3.2 um
6020 0 BONDPAD.B.1B: Bondpad Metal11 beveled segments must be >= 1.8 um and <= 3.2 um
6023 0 BONDPAD.SP.3: Bondpad Via1 to Bondpad Via1 spacing must be >= 0.22 um
6026 0 BONDPAD.SP.3: Bondpad Via2 to Bondpad Via2 spacing must be >= 0.22 um
6029 0 BONDPAD.SP.3: Bondpad Via3 to Bondpad Via3 spacing must be >= 0.22 um
6032 0 BONDPAD.SP.3: Bondpad Via4 to Bondpad Via4 spacing must be >= 0.22 um
6035 0 BONDPAD.SP.3: Bondpad Via5 to Bondpad Via5 spacing must be >= 0.22 um
6038 0 BONDPAD.SP.3: Bondpad Via6 to Bondpad Via6 spacing must be >= 0.22 um
6041 0 BONDPAD.SP.4: Bondpad Via7 to Bondpad Via7 spacing must be >= 0.22 um
6044 0 BONDPAD.SP.4: Bondpad Via8 to Bondpad Via8 spacing must be >= 0.22 um
6047 0 BONDPAD.SP.4: Bondpad Via9 to Bondpad Via9 spacing must be >= 0.54 um
6050 0 BONDPAD.SP.4: Bondpad Via10 to Bondpad Via10 spacing must be >= 0.54 um
6052 0 BONDPAD.E.2: Bondpad Metal1 to Via1 enclosure must be >= 0.05 um
6054 0 BONDPAD.E.2: Bondpad Metal1 to Via1 enclosure must be >= 0.05 um
6056 0 BONDPAD.E.2: Bondpad Metal2 to Via2 enclosure must be >= 0.05 um
6058 0 BONDPAD.E.2: Bondpad Metal2 to Via2 enclosure must be >= 0.05 um
6060 0 BONDPAD.E.2: Bondpad Metal3 to Via3 enclosure must be >= 0.05 um
6062 0 BONDPAD.E.2: Bondpad Metal3 to Via3 enclosure must be >= 0.05 um
6064 0 BONDPAD.E.2: Bondpad Metal4 to Via4 enclosure must be >= 0.05 um
6066 0 BONDPAD.E.2: Bondpad Metal4 to Via4 enclosure must be >= 0.05 um
6068 0 BONDPAD.E.2: Bondpad Metal5 to Via5 enclosure must be >= 0.05 um
6070 0 BONDPAD.E.2: Bondpad Metal5 to Via5 enclosure must be >= 0.05 um
6072 0 BONDPAD.E.2: Bondpad Metal6 to Via6 enclosure must be >= 0.05 um
6074 0 BONDPAD.E.2: Bondpad Metal6 to Via6 enclosure must be >= 0.05 um
6076 0 BONDPAD.E.3: Bondpad Metal7 to Via7 enclosure must be >= 0.05 um
6078 0 BONDPAD.E.3: Bondpad Metal7 to Via7 enclosure must be >= 0.05 um
6080 0 BONDPAD.E.3: Bondpad Metal8 to Via8 enclosure must be >= 0.05 um
6082 0 BONDPAD.E.3: Bondpad Metal8 to Via8 enclosure must be >= 0.05 um
6084 0 BONDPAD.E.3: Bondpad Metal9 to Via9 enclosure must be >= 0.09 um
6086 0 BONDPAD.E.3: Bondpad Metal9 to Via9 enclosure must be >= 0.09 um
6088 0 BONDPAD.E.3: Bondpad Metal9 to Via10 enclosure must be >= 0.09 um
6090 0 BONDPAD.E.3: Bondpad Metal9 to Via10 enclosure must be >= 0.09 um
6092 0 BONDPAD.E.2: Bondpad Metal2 to Via1 enclosure must be >= 0.05 um
6094 0 BONDPAD.E.2: Bondpad Metal2 to Via1 enclosure must be >= 0.05 um
6096 0 BONDPAD.E.2: Bondpad Metal3 to Via2 enclosure must be >= 0.05 um
6098 0 BONDPAD.E.2: Bondpad Metal3 to Via2 enclosure must be >= 0.05 um
6100 0 BONDPAD.E.2: Bondpad Metal4 to Via3 enclosure must be >= 0.05 um
6102 0 BONDPAD.E.2: Bondpad Metal4 to Via3 enclosure must be >= 0.05 um
6104 0 BONDPAD.E.2: Bondpad Metal5 to Via4 enclosure must be >= 0.05 um
6106 0 BONDPAD.E.2: Bondpad Metal5 to Via4 enclosure must be >= 0.05 um
6108 0 BONDPAD.E.2: Bondpad Metal6 to Via5 enclosure must be >= 0.05 um
6110 0 BONDPAD.E.2: Bondpad Metal6 to Via5 enclosure must be >= 0.05 um
6112 0 BONDPAD.E.2: Bondpad Metal7 to Via6 enclosure must be >= 0.05 um
6114 0 BONDPAD.E.2: Bondpad Metal7 to Via6 enclosure must be >= 0.05 um
6116 0 BONDPAD.E.3: Bondpad Metal8 to Via7 enclosure must be >= 0.05 um
6118 0 BONDPAD.E.3: Bondpad Metal8 to Via7 enclosure must be >= 0.05 um
6120 0 BONDPAD.E.3: Bondpad Metal9 to Via8 enclosure must be >= 0.05 um
6122 0 BONDPAD.E.3: Bondpad Metal9 to Via8 enclosure must be >= 0.05 um
6124 0 BONDPAD.E.3: Bondpad Metal10 to Via9 enclosure must be >= 0.09 um
6126 0 BONDPAD.E.3: Bondpad Metal10 to Via9 enclosure must be >= 0.09 um
6128 0 BONDPAD.E.3: Bondpad Metal11 to Via10 enclosure must be >= 0.09 um
6130 0 BONDPAD.E.3: Bondpad Metal11 to Via10 enclosure must be >= 0.09 um
6131 0 BONDPAD.SP.6: Bondpad Metal1 to Bondpad Metal1 spacing across first slot must be >= 1.00 um and <= 3.50 um
6132 0 BONDPAD.SP.6: Bondpad Metal1 to Bondpad Metal1 spacing across first slot must be >= 1.00 um and <= 3.50 um
6133 0 BONDPAD.SP.6: Bondpad Metal2 to Bondpad Metal2 spacing across first slot must be >= 1.00 um and <= 3.50 um
6134 0 BONDPAD.SP.6: Bondpad Metal2 to Bondpad Metal2 spacing across first slot must be >= 1.00 um and <= 3.50 um
6135 0 BONDPAD.SP.6: Bondpad Metal3 to Bondpad Metal3 spacing across first slot must be >= 1.00 um and <= 3.50 um
6136 0 BONDPAD.SP.6: Bondpad Metal3 to Bondpad Metal3 spacing across first slot must be >= 1.00 um and <= 3.50 um
6137 0 BONDPAD.SP.6: Bondpad Metal4 to Bondpad Metal4 spacing across first slot must be >= 1.00 um and <= 3.50 um
6138 0 BONDPAD.SP.6: Bondpad Metal4 to Bondpad Metal4 spacing across first slot must be >= 1.00 um and <= 3.50 um
6139 0 BONDPAD.SP.6: Bondpad Metal5 to Bondpad Metal5 spacing across first slot must be >= 1.00 um and <= 3.50 um
6140 0 BONDPAD.SP.6: Bondpad Metal5 to Bondpad Metal5 spacing across first slot must be >= 1.00 um and <= 3.50 um
6141 0 BONDPAD.SP.6: Bondpad Metal6 to Bondpad Metal6 spacing across first slot must be >= 1.00 um and <= 3.50 um
6142 0 BONDPAD.SP.6: Bondpad Metal6 to Bondpad Metal6 spacing across first slot must be >= 1.00 um and <= 3.50 um
6143 0 BONDPAD.SP.6: Bondpad Metal7 to Bondpad Metal7 spacing across first slot must be >= 1.00 um and <= 3.50 um
6144 0 BONDPAD.SP.6: Bondpad Metal7 to Bondpad Metal7 spacing across first slot must be >= 1.00 um and <= 3.50 um
6145 0 BONDPAD.SP.6: Bondpad Metal8 to Bondpad Metal8 spacing across first slot must be >= 1.00 um and <= 3.50 um
6146 0 BONDPAD.SP.6: Bondpad Metal8 to Bondpad Metal8 spacing across first slot must be >= 1.00 um and <= 3.50 um
6147 0 BONDPAD.SP.6: Bondpad Metal9 to Bondpad Metal9 spacing across first slot must be >= 1.00 um and <= 3.50 um
6148 0 BONDPAD.SP.6: Bondpad Metal9 to Bondpad Metal9 spacing across first slot must be >= 1.00 um and <= 3.50 um
6149 0 BONDPAD.SP.6: Bondpad Metal10 to Bondpad Metal10 spacing across first slot must be >= 1.00 um and <= 3.50 um
6150 0 BONDPAD.SP.6: Bondpad Metal10 to Bondpad Metal10 spacing across first slot must be >= 1.00 um and <= 3.50 um
6152 0 BONDPAD.SP.7: Bondpad Via1 array to Bondpad Via1 array spacing must be >= 1.1 um
6154 0 BONDPAD.SP.7: Bondpad Via2 array to Bondpad Via2 array spacing must be >= 1.1 um
6156 0 BONDPAD.SP.7: Bondpad Via3 array to Bondpad Via3 array spacing must be >= 1.1 um
6158 0 BONDPAD.SP.7: Bondpad Via4 array to Bondpad Via4 array spacing must be >= 1.1 um
6160 0 BONDPAD.SP.7: Bondpad Via5 array to Bondpad Via5 array spacing must be >= 1.1 um
6162 0 BONDPAD.SP.7: Bondpad Via6 array to Bondpad Via6 array spacing must be >= 1.1 um
6164 0 BONDPAD.SP.7: Bondpad Via7 array to Bondpad Via7 array spacing must be >= 1.1 um
6166 0 BONDPAD.SP.7: Bondpad Via8 array to Bondpad Via8 array spacing must be >= 1.1 um
6168 0 BONDPAD.SP.7: Bondpad Via9 array to Bondpad Via9 array spacing must be >= 1.1 um
6170 0 BONDPAD.SP.7: Bondpad Via10 array to Bondpad Via10 array spacing must be >= 1.1 um
6173 0 OXIDER.W.1.1: Minimum Active Resistor width >= 0.1 um
6176 0 POLYR.W.1.1: Minimum Poly resistor width >= 0.1 um
